application: millzor2890
version: 1
runtime: python27
api_version: 1
threadsafe: true


  
libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: django
  version: latest
  
handlers:
- url: /static
  static_dir: static
  
- url: /.*
  script: blog.application